Your job is to determine the name of a book based on the content given in the
document (in the DOCUMENT section). The document will be a short excerpt
from the content of the book. The title of the book may or may not be explicitly
stated in the document. If the title is not explicitly stated, set the title
to "UNKNOWN".

If the title is explicitly stated in the content, then it should be given in
title case.

DOCUMENT:
{document}